### ISSUE TITLE
Signage needs Updated

### ISSUE THREAD

**Issue by fbertsch** [mozilla/magdalena#5]
Currently, there is a big scary orange sign that says "This is not UT data", except on the right side, there is UT data. I would say the sign needs updated, or at least specify that it's the Socorro data on the left side that it not UT, and the right side is UT.

**Comment by calixteman** [comment]
Fixed in https://github.com/mozilla/magdalena/commit/3d743ee663414b390b6cf960cf184b2ad5d86fee
Feel free to make a PR or to give me the exact text you want if you're not ok with this one.
